name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.0
  path: ^1.8.0
  open_file: ^3.2.1
  file_picker: ^5.2.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  google_fonts: ^6.1.0
  cloud_firestore: ^4.12.1
  flutter_svg: ^2.0.8
  mime: ^1.0.0
  fluttertoast: ^8.0.8
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  table_calendar: ^3.0.0
  intl: ^0.18.0
  image_picker: ^1.1.2  # Moved image_picker to the correct position

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/imgs/logo.jpg
    - asset/icons/assignment.svg
    - asset/icons/resume.svg
    - asset/
    - asset/icons/chat.svg
    - asset/icons/document.svg
    - asset/icons/timetable.svg
    - asset/icons/check.svg
    - asset/icons/profile.svg
    - asset/icons/teacher.svg
    - asset/icons/student.svg
    - asset/icons/parent.svg
    - asset/icons/classroom.svg
    - asset/icons/addpost.svg
    - asset/icons/result.svg
    - asset/icons/ask.svg
    - asset/icons/gallery.svg
    - asset/icons/event.svg

    

    