const express = require('express');
const { downloadFile,GetAssignById,GetMessageByClassname,getStudentData ,deleteStudent,editStudent} = require('../controllers/studentController');
const router = express.Router();
router.get('/downloadFile/:fileId',downloadFile );
router.get('/getassi/:userId',GetAssignById );
router.post('/student/editStudent',editStudent );
router.delete('/deletestudents/:studentId', deleteStudent);
router.get('/getmess/:classname',GetMessageByClassname);
router.get('/getstudent/:userId',getStudentData);
module.exports = router;
