const express = require('express');
const {getStudentGrades,addSubmission,upload,getAssignments,downloadFile,GetAssignById,GetMessageByClassname,getStudentData ,deleteStudent,editStudent} = require('../controllers/studentController');
const router = express.Router();
router.get('/getassi/:userId', getAssignments);
router.post('/addSubmission', upload, addSubmission);
router.get('/downloadFile/:fileId',downloadFile );
router.get('/getassi/:userId',GetAssignById );
router.post('/student/editStudent',editStudent );
router.delete('/deletestudents/:studentId', deleteStudent);
router.get('/getmess/:classname',GetMessageByClassname);
router.get('/getstudent/:userId',getStudentData);
router.get('/student/grades', getStudentGrades);
module.exports = router;
