const express = require('express');
const {upload,downloadAssignment, uploadStudentAssignment,getAssignments,downloadFile,GetAssignById,GetMessageByClassname,getStudentData ,deleteStudent,editStudent} = require('../controllers/studentController');
const router = express.Router();
router.get('/getassi/:userId', getAssignments);
router.post('/uploadassi', upload, uploadStudentAssignment);
router.get('/download/:fileId', downloadAssignment);
router.get('/downloadFile/:fileId',downloadFile );
router.get('/getassi/:userId',GetAssignById );
router.post('/student/editStudent',editStudent );
router.delete('/deletestudents/:studentId', deleteStudent);
router.get('/getmess/:classname',GetMessageByClassname);
router.get('/getstudent/:userId',getStudentData);
module.exports = router;
